<?php
return [
    // ["/other/aboutme.php","About the Owner"],
    ["/other/about.php","About the Server"],
    ["/app","App"],
    // ["/apt-mirror","Apt Mirror"],
    ["/game/v2#tabs-2","Battleship","Play some battleship!"],
    ["/game/v2","Board Games","Play a board game"],
    ["/game/generator/baby.php","Baby Names"],
    ["/calculator","Calculator"],
    ["/deercoin/casino.php","Casino","Gamble away your DataDeer life savings!"],
    ["/deercoin","Currency","Invest in DeerCoin!"],
    ["/cp","Cyber Patriots"],
    ["/other/changelog.php","Changelog","See what's new!"],
    ["/chats/gchat","Chat - Group","Join a groupchat!"],
    ["/chats/pchat","Chat - Private","Have a private chat in privacy"],
    ["/game/v2#tabs-1","Checkers","A nice game of checkers?"],
    ["/game/v2#tabs-0","Chess","Play some intellectually challenging chess!"],
    ["/game/v2#tabs-6","Connect 4","Connect four tokens to win this game!"],
    ["/deercoin","Deercoin"],
    ["/dog","Dog - The History of the Domestic Dog","Learn about dogs!"],
    ["/dognet","DogNet - Give me a potential dog image!","Upload an image to see if it has a dog in it!"],
    ["/directory","Directory"],
    ["/share","File Pile"],
    ["/game/generator/fortune.php","Fortunes"],
    ["/game/v2","Games!"],
    ["/chats/gchat","Group Chat"],
    ["/game/generator/insult.php","Insults"],
    ["/learn","Learn"],
    ["/lifestream","Lifestream"],
    ["/game/libs","MadLibs&#8482;","Play some madlibs!"],
    ["/lifestream","Map","Put yourself on the map (literally)!"],
    // ["/merch","Merch"],
    ["/other/minecraft.php","Minecraft"],
    ["/game/v2#tabs-3","Minesweeper"],
    ["/chats/pchat","Private Chat"],
    ["/rs/","Raspberry Sprinkler"],
    // ["/directory","Recursion - Definition"],
    ["/other/share.php","Share"],
    // ["/chats/schat","Secure Chat"],
    ["/search","Search Engine (webpages and images)"],
    ["/other/settings.php","Settings"],
    ["/sewer","Sewer"],
    ["/share","Share"],
    ["/game/v2#tabs-4","Sudoku","Play some challenging Sudoku!"],
    ["https://github.com/zaners123/DataDeer","Source Code"],
    ["/golduser","Subscription Menu"],
    ["/learn/tech","Tech - Learn IT"],
    ["/other/terraria.php","Terraria"],
    ["/test","Tests","Take an IQ Test!"],
    ["/game/v2/#tabs-5","Tic Tac Toe","A nice game of Tic Tac Toe with a chum!"],
    ["/other/tor.php","Tor"],
    ["/21","Twenty One (No, not the band...)"],
    ["/weather","Weather (In Kelvin, too!)"],
];